import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import navbar from "./components/navbar";
import Nav from"./components/navbar"
import Main from "./components/bady"
const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Testing PlatForm App",
  description: "Generated by Testing Platform Team",

};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    
    <html lang="en">
      
      <body className={`${inter.className} bg-slate-900 text-slate-100 text-lg min-h-screen `}>
      
        <Nav></Nav>

      
        {children}</body>
    </html>
  );
}
